/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 NetworkingCardFloat.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF, Float } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/NetworkingCardFloat-transformed.glb')
  return (
    <Float translateZ={-10} speed={0.5} rotationIntensity={1}
    floatIntensity={0.1}
    >
    <group {...props} dispose={null}>
      <mesh scale={2.5} geometry={nodes.Plane.geometry} material={materials.NetworkingCardTexture} />
    </group>
    </Float>
  )
}

useGLTF.preload('/NetworkingCardFloat-transformed.glb')
